UpdatedLeadership
AdamJablonka/qc-physics-club-website pull request #36
Opened 2024-03-24 18:10 UTC by ChristianASC22

Swan and Maeve leadership positions fixed in About section.

2024-03-24 18:17 UTC, AdamJablonka requested changes

2024-03-24 18:17 UTC, AdamJablonka commented on app/about/page.tsx
> +              Meave (something)
You should ask Swan for her last name, instead of leaving it as (something), you don't want to push (something) to the website

2024-03-24 18:37 UTC, ChristianASC22 reviewed
Maeve's last name was added.

2024-03-24 21:22 UTC, AdamJablonka requested changes
Awesome this looks great, while you're here, wanna make things more scalable?

We should create an object, with their names, before the render area of the code file. I'll give you a hint here without the types involved so you can infer.

Something like:
`BoardMemberNames= {
   president: "Swan Htet",
   vicePresident: "Meave Cheevers"
   secretary: "Anand Persaud"
   treasurer: "Ryan Persad"
}`

Then do you know how you would replace the names within the typography component with these?
something like `{BoardMemberNames.?}`

This allows it to be easier and more scalable in the future when the next board members are enlisted next semester.

2024-03-24 23:17 UTC, ChristianASC22 reviewed
In object form.

2024-03-26 01:19 UTC, AdamJablonka commented
Looks great

2024-03-26 01:19 UTC, AdamJablonka approved these changes
LGTM!

2024-03-26 01:20 UTC, merged